### ISSUE TITLE
Email config seems broken

### ISSUE THREAD

**Issue by alexisLefebvre** [Troopers/BehatContexts#21]
In one project, we used the 0.5 version of this bundle with this configuration:

```
        Troopers\BehatContexts\Extension:
            alias_entity:
                enabled: true
            mails:
                path: "features/bootstrap/emailsConfig"
                key: project_emails
```

The tests worked.

After updating to `troopers/behat-contexts:1.0.0-beta.4`, it throws an error:

```
  [Symfony\Component\Config\Definition\Exception\InvalidTypeException]                        
  Invalid type for path "testwork.troopers_behat.mails.path". Expected array, but got string  
```

So I declared an array under `path:`

```
        Troopers\BehatContexts\Extension:
            alias_entity:
                enabled: true
            mails:
                path:
                    - features/bootstrap/emailsConfig
                key: project_emails
```

And I have another error:

```
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized option "0" under "testwork.troopers_behat.mails.path"             
```

If `path` is an array, how will it work since the reader expects a string?

The `path` varialble will be passed to`$this->reader->load(…);` on the following line: https://github.com/Troopers/BehatContexts/blob/9b3c1e54cff098da8593f72237fa89650c83cfdb/src/Troopers/BehatContexts/Parser/Mail/MailParser.php#L34

But it looks like the file reader expects a string and not an array: https://github.com/Troopers/BehatContexts/blob/9b3c1e54cff098da8593f72237fa89650c83cfdb/src/Troopers/BehatContexts/Component/ConfigReader.php#L39

This may be related to #15 because if I revert this change (I remove the [`->prototype('array')` line](https://github.com/Troopers/BehatContexts/pull/15/files#diff-c54bd0193b02d176be9ac997cffad4caR65)), it works with the first configuration.
